# Generated by Django 3.2.6 on 2021-09-13 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0005_auto_20210912_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='fav_by',
            field=models.ManyToManyField(related_name='fav_item', to='store_app.User'),
        ),
        migrations.AlterField(
            model_name='item',
            name='purchase_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchased_item', to='store_app.user'),
        ),
    ]
