# Generated by Django 3.2.6 on 2021-09-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0006_auto_20210912_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='purchase_by',
        ),
    ]
