# Generated by Django 3.2.6 on 2021-09-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0009_alter_item_fav_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='added_item',
            field=models.ManyToManyField(related_name='cart_item', to='store_app.User'),
        ),
    ]
